roles:
  admin: 1
  normal: 0
provider:
  google: "google_oauth2"
  facebook: "facebook"
  twitter: "twitter"
  linkedin: "linkedin"
directional:
  address:
    new: "Create New Address"
image_sample:
  - /app/assets/images/house1.jpg
  - /app/assets/images/house2.jpg
  - /app/assets/images/house3.jpg
user:
  avatar_default: "avatar_default.jpg"  
