roles:
  admin: 1
  normal: 0
provider:
  google: "google_oauth2"
  facebook: "facebook"
  twitter: "twitter"
  linkedin: "linkedin"
directional:
  address:
    new: "Create New Address"
image_sample:
  - /app/assets/images/house1.jpg
  - /app/assets/images/house2.jpg
  - /app/assets/images/house3.jpg
user:
  avatar_default: "avatar_default.jpg"
num_of_recent_addresses: 10
num_of_show_location: 5
num_of_address_by_regions: 5
pagination:
  per_page: 10
locations:
  bacgiang: "Bac Giang"
  backan: "Bac Kan"
  caobang: "Cao Bang"
  hagian: "Ha Giang"
  langsong: "Lang Son"
  phutho: "Phu Tho"
  quangninh: "Quang Ninh"
  thainguyen: "Thai Nguyen"
  tuyenquang: "Tuyen Quang"
  laocai: "Lao Cai"
  yenbai: "Yen Bai"
  dienbien: "Dien Bien"
  hoabinh: "Hoa Binh"
  laichau: "Lai Chau"
  sonla: "Son La"
  bacninh: "Bac Ninh"
  hanam: "Ha Nam"
  haiduong: "Hai Duong"
  hungyen: "Hung Yen"
  namdinh: "Nam Dinh"
  ninhbinh: "Ninh Binh"
  thaibinh: "Thai Binh"
  vinhphuc: "Vinh Phuc"
  hanoi: "Ha Noi"
  haiphong: "Ha Phong"
  hatinh: "Ha Tinh"
  nghean: "Nghe An"
  quangbinh: "Quang Binh"
  quangtri: "Quang Tri"
  thanhhoa: "Thanh Hoa"
  hue: "Hue"
  daknong: "Dak Nong"
  gialai: "Gia Lai"
  kontum: "Kon Tum"
  lamdong: "Lam Dong"
  binhdinh: "binhdinh"
  binhthuan: "Binh Thuan"
  khanhhoa: "Khanh Hoa"
  ninhhthuan: "Ninh Thuan"
  phuyen: "Phu Yen"
  quangnam: "Quang Nam"
  quangngai: "Quang Ngai"
  danang: "Da Nang"
  baria: "Ba Ria"
  binhduong: "Binh Duong"
  binhphuoc: "Binh Phuong"
  dongnai: "Dong Nai"
  tayninh: "Tay Ninh"
  HCM: "HCM"
  angiang: "An Giang"
  baclieu: "Bac Lieu"
  bentre: "Ben Tre"
  camau: "Ca Mau"
  dongthap: "Dong Thap"
  haugiang: "Hau Giang"
  kiengiang: "Kien Giang"
  longan: "Long An"
  soctrang: "Soc Trang"
  tiengiang: "Tien Giang"
  travinh: "Tra Vinh"
  vinhlong: "Vinh Long"
  cantho: "Can Tho"
  vinh: "Vinh"
prices:
  0: 0
  1.0 M: 1000000
  2.0 M: 2000000
  3.0 M: 3000000
  4.0 M: 4000000
  5.0 M: 5000000
  6.0 M: 6000000
  7.0 M: 7000000
  8.0 M: 8000000
  9.0 M: 9000000
  10.0 M: 10000000
  20.0 M: 20000000
  30.0 M: 30000000
  40.0 M: 40000000
  50.0 M: 50000000
  60.0 M: 60000000
  70.0 M: 70000000
  80.0 M: 80000000
  90.0 M: 90000000
  100.0 M: 100000000
squares:
  0: 0
  5.0: 5
  10.0: 10
  15.0: 15
  20.0: 20
  25.0: 25
  30.0: 30
  35.0: 35
  40.0: 40
  45.0: 45
  50.0: 50
  55.0: 55
  60.0: 60
  65.0: 65
  70.0: 70
  75.0: 75
  80.0: 80
  85.0: 85
  90.0: 90
  100.0: 100
facilities:
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: 10
  11: 11
  12: 12
  13: 13
  14: 14
  15: 15
  16: 16
  17: 17
  18: 18
  19: 19
  20: 20
  21: 21
  22: 22
  23: 23
  24: 24
  25: 25
  26: 26
  27: 27
  28: 28
  29: 29
  30: 30
  31: 31
  32: 32
  33: 33
  34: 34
  35: 35
  36: 36
  37: 37
  38: 38
  39: 39
  40: 40
images:
  house_image: "house-thumb.jpg"
review:
  upload_icon: "upload_img.png"
  zero: 0
chat:
  img_size: "20x20"
  type:
    new_message: "new_message"
    connected: "connected"
    disconnected: "disconnected"
type:
  title: "Title"
  price_low_high: "Price: Low to High"
  price_high_low: "Price: High to Low"
  square_small_big: "Square: Small to Big"
  square_big_small: "Square: Big to Small"
  capacity_low_high: "Capicity: Low to High"
  capacity_high_low: "Capicity: High to Low"
